#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --edit
if ! git rev-parse --git-dir/hooks/commit-msg "$1"; then
  echo "Failed to execute commit-msg hook, but continuing with commit."
fi